[package]
name = "get-arch-news"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minidom = "0.15.1"
reqwest = {version = "0.11.17", features = ["blocking"]}
